---
version: "3"

services:
  powerdnsapi-dev:
    volumes:
      - "${PWD}:/source"
    build:
      context: "${PWD}"
      dockerfile: "development/Dockerfile"
      args:
        PYTHON_VER: "${PYTHON_VER}"

# TODO: Add PowerDNS Server
